apiVersion: kueue.x-k8s.io/v1beta2
kind: ClusterQueue
metadata:
  name: nightly-eval
spec:
  namespaceSelector: {}
  preemption:
    withinClusterQueue: Never
    reclaimWithinCohort: Never
  resourceGroups:
    - coveredResources: ["cpu", "memory", "nvidia.com/gpu", "ephemeral-storage"]
      flavors:
        - name: gb200
          resources:
            - name: "cpu"
              nominalQuota: 320
            - name: "memory"
              nominalQuota: "5120Gi"
            - name: "nvidia.com/gpu"
              nominalQuota: 40
            - name: "ephemeral-storage"
              nominalQuota: "1280Gi"
  queueingStrategy: StrictFIFO
