apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: nightly-
resources:
  - ../../../j-llm-d/gb200/overlays/pd
patches:
  - path: ../kueue-labels-patch.yaml
    target:
      kind: LeaderWorkerSet
