inferenceExtension:
  replicas: 1
  image:
    registry: ghcr.io
    repository: llm-d/llm-d-inference-scheduler
    tag: v0.8.0
  extProcPort: 9002
  monitoring:
    interval: "10s"
    prometheus:
      enabled: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values: ["amd64"]
  resources:
    requests:
      cpu: "8"
      memory: 16Gi
    limits:
      cpu: "8"
      memory: 16Gi

inferencePool:
  name: ${DEPLOY_NAME}-infpool
  targetPorts:
    - number: 8000
    - number: 8001
    - number: 8002
    - number: 8003
  modelServers:
    matchLabels:
      llm-d.ai/inference-serving: "true"
      llm-d.ai/model: DeepSeek-V4-Pro
      llm-d.ai/deployment: pd
      llm-d.ai/owner: ${OWNER}

provider:
  name: istio
  istio:
    destinationRule:
      host: ${DEPLOY_NAME}-infpool-epp
      trafficPolicy:
        tls:
          insecureSkipVerify: true
          mode: SIMPLE
        connectionPool:
          http:
            http1MaxPendingRequests: 256000
            maxRequestsPerConnection: 256000
            http2MaxRequests: 256000
            idleTimeout: "900s"
          tcp:
            maxConnections: 256000
            maxConnectionDuration: "1800s"
            connectTimeout: "900s"
